const AUTOWRITER_SERVICE_URL = process.env.AUTOWRITER_SERVICE_URL || 'http://127.0.0.1:7001';
const AUTOWRITER_TIMEOUT_MS = Number(process.env.AUTOWRITER_TIMEOUT_MS || 15000);

module.exports = {
  AUTOWRITER_SERVICE_URL,
  AUTOWRITER_TIMEOUT_MS,
};
